### PR TITLE
Adapt postman collection to test in iWorkflow use cases.

### PR DESCRIPTION
**Pull request by RafalKorepta**
@0xHiteshPatel @KrystianMarek 

WIP! One use cases is disabled f5-https-waf-lb.

#### What issues does this address?
Create command line tool that will test iWorkflow use cases.

#### What's this change do?
Add new test runner (newman with f5 specyfic functionality).

#### Where should the reviewer start?
Run new test runner by:
./build.py -nd
cd test/f5-postman-workflows/workflows/
node ../framework/f5-newman-wrapper/f5-newman-wrapper iWf_test.json
node ../framework/f5-newman-wrapper/f5-newman-wrapper iWf_clenup.json

EXPECT: All newman collection should pass without errors.

### CODE REVIEW

**Comment by KrystianMarek** [comment]
```
$ node ../framework/f5-newman-wrapper/f5-newman-wrapper iWf_test.json 
/home/marek/Development/f5-application-services-integration-iApp/test/f5-postman-workflows/framework/f5-newman-wrapper/f5-newman-wrapper:51
var printOut = function(str, level=1, func=console.log) {
                                  ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by RafalKorepta** [comment]
Sory for wrong instruction. 

./build.py -nd
cd test/f5-postman-workflows/framework/
npm install
npm run build
cd f5-newman-wrapper/
npm install
cd ../../workflows/
node ../framework/f5-newman-wrapper/f5-newman-wrapper iWf_test.json
node ../framework/f5-newman-wrapper/f5-newman-wrapper iWf_clenup.json

That should be enough.

**Comment by KrystianMarek** [comment]
same thing

**Comment by RafalKorepta** [comment]
Please test it with node in version at least v6.10.2 and npm in version at 3.10.10.

**Pull request merged**
